//
// Created by 赵英坤 on 2018/9/7.
//

#ifndef TESTFFMPEG_CMD_H
#define TESTFFMPEG_CMD_H

#endif //TESTFFMPEG_CMD_H

char *json = const_cast<char *>("[\n"
        "    {\n"
        "        \"uid\": \"comp-1\",\n"
        "        \"flags\": 0,\n"
        "        \"width\": 544,\n"
        "        \"height\": 960,\n"
        "        \"inFrame\": 0,\n"
        "        \"outFrame\": 368,\n"
        "        \"compName\": \"导出\",\n"
        "        \"layers\": [\n"
        "            {\n"
        "                \"uid\": \"solid-1-52\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-1410\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#ffffff\",\n"
        "                \"inFrame\": 0,\n"
        "                \"outFrame\": 368,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 480,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-51\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-128\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 0,\n"
        "                \"outFrame\": 24,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-51-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-50\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 8,\n"
        "                \"srcId\": \"image-23\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 24,\n"
        "                \"outFrame\": 56,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-50-transform2d.json\"\n"
        "                },\n"
        "                \"effects\": [\n"
        "                    {\n"
        "                        \"category\": 2,\n"
        "                        \"typename\": 1,\n"
        "                        \"showname\": \"tint\",\n"
        "                        \"animated\": false,\n"
        "                        \"atom\": {\n"
        "                            \"alpha\": 1,\n"
        "                            \"black\": \"#000000\",\n"
        "                            \"white\": \"#ffffff\"\n"
        "                        }\n"
        "                    }\n"
        "                ]\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-49\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-23\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 56,\n"
        "                \"outFrame\": 72,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-49-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-48\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 2,\n"
        "                \"srcId\": \"image-61\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 72,\n"
        "                \"outFrame\": 87,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-48-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-47\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-90\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"color\": \"#ffffff\",\n"
        "                \"inFrame\": 72,\n"
        "                \"outFrame\": 87,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 240,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 240,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-46\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 2,\n"
        "                \"srcId\": \"image-61\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 72,\n"
        "                \"outFrame\": 87,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-46-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-45\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-90\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"color\": \"#ffffff\",\n"
        "                \"inFrame\": 72,\n"
        "                \"outFrame\": 87,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 240,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 720,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-44\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-553\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"color\": \"#ffe9c6\",\n"
        "                \"inFrame\": 72,\n"
        "                \"outFrame\": 87,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 240,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 240,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-43\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-576\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"color\": \"#80daff\",\n"
        "                \"inFrame\": 72,\n"
        "                \"outFrame\": 87,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 240,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 720,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-42\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 10,\n"
        "                \"srcId\": \"image-600\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 87,\n"
        "                \"outFrame\": 94,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 480,\n"
        "                        \"sx\": 1.00162162162162,\n"
        "                        \"sy\": 1.00162162162162,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                },\n"
        "                \"effects\": [\n"
        "                    {\n"
        "                        \"category\": 2,\n"
        "                        \"typename\": 1,\n"
        "                        \"showname\": \"tint\",\n"
        "                        \"animated\": false,\n"
        "                        \"atom\": {\n"
        "                            \"alpha\": 1,\n"
        "                            \"black\": \"#000000\",\n"
        "                            \"white\": \"#ffffff\"\n"
        "                        }\n"
        "                    }\n"
        "                ]\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-41\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-593\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"color\": \"#ffffff\",\n"
        "                \"inFrame\": 87,\n"
        "                \"outFrame\": 94,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 160,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 160,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-40\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 10,\n"
        "                \"srcId\": \"image-600\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 94,\n"
        "                \"outFrame\": 101,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 480,\n"
        "                        \"sx\": 1.00162162162162,\n"
        "                        \"sy\": 1.00162162162162,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                },\n"
        "                \"effects\": [\n"
        "                    {\n"
        "                        \"category\": 2,\n"
        "                        \"typename\": 1,\n"
        "                        \"showname\": \"tint\",\n"
        "                        \"animated\": false,\n"
        "                        \"atom\": {\n"
        "                            \"alpha\": 1,\n"
        "                            \"black\": \"#000000\",\n"
        "                            \"white\": \"#ffffff\"\n"
        "                        }\n"
        "                    }\n"
        "                ]\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-39\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-593\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"color\": \"#ffffff\",\n"
        "                \"inFrame\": 94,\n"
        "                \"outFrame\": 101,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 160,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 480,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-38\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 10,\n"
        "                \"srcId\": \"image-600\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 101,\n"
        "                \"outFrame\": 110,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 480,\n"
        "                        \"sx\": 1.00162162162162,\n"
        "                        \"sy\": 1.00162162162162,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                },\n"
        "                \"effects\": [\n"
        "                    {\n"
        "                        \"category\": 2,\n"
        "                        \"typename\": 1,\n"
        "                        \"showname\": \"tint\",\n"
        "                        \"animated\": false,\n"
        "                        \"atom\": {\n"
        "                            \"alpha\": 1,\n"
        "                            \"black\": \"#000000\",\n"
        "                            \"white\": \"#ffffff\"\n"
        "                        }\n"
        "                    }\n"
        "                ]\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-37\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-593\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"color\": \"#ffffff\",\n"
        "                \"inFrame\": 101,\n"
        "                \"outFrame\": 110,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 160,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 800,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-36\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-600\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 110,\n"
        "                \"outFrame\": 124,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-36-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-35\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-99\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 124,\n"
        "                \"outFrame\": 166,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 480,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-34\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 41,\n"
        "                \"srcId\": \"image-99\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 147,\n"
        "                \"outFrame\": 186,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 480,\n"
        "                        \"sx\": 1.06617647058824,\n"
        "                        \"sy\": 1.06617647058824,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                },\n"
        "                \"maskGroup\": {\n"
        "                    \"mode\": [\n"
        "                        1\n"
        "                    ],\n"
        "                    \"alpha\": [\n"
        "                        1\n"
        "                    ]\n"
        "                },\n"
        "                \"effects\": [\n"
        "                    {\n"
        "                        \"category\": 2,\n"
        "                        \"typename\": 1,\n"
        "                        \"showname\": \"tint\",\n"
        "                        \"animated\": false,\n"
        "                        \"atom\": {\n"
        "                            \"alpha\": 1,\n"
        "                            \"black\": \"#000000\",\n"
        "                            \"white\": \"#ffffff\"\n"
        "                        }\n"
        "                    }\n"
        "                ]\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-33\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 2,\n"
        "                \"srcId\": \"image-334\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 166,\n"
        "                \"outFrame\": 204,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-33-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-32\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-373\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"color\": \"#ffffff\",\n"
        "                \"inFrame\": 166,\n"
        "                \"outFrame\": 204,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"solid-1-32-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-31\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-552\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"color\": \"#ffe1ad\",\n"
        "                \"inFrame\": 195,\n"
        "                \"outFrame\": 204,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 160,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 800,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-30\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 2,\n"
        "                \"srcId\": \"image-334\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 166,\n"
        "                \"outFrame\": 204,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-30-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-29\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-373\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"color\": \"#ffffff\",\n"
        "                \"inFrame\": 166,\n"
        "                \"outFrame\": 204,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"solid-1-29-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-28\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 2,\n"
        "                \"srcId\": \"image-334\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 166,\n"
        "                \"outFrame\": 204,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-28-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-27\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-373\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"color\": \"#ffffff\",\n"
        "                \"inFrame\": 166,\n"
        "                \"outFrame\": 204,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"solid-1-27-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-26\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-502\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 320,\n"
        "                \"color\": \"#dd8dff\",\n"
        "                \"inFrame\": 195,\n"
        "                \"outFrame\": 204,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 160,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 160,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-25\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-632\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 204,\n"
        "                \"outFrame\": 252,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-25-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-24\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-816\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#ffb4e7\",\n"
        "                \"inFrame\": 210,\n"
        "                \"outFrame\": 223,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"solid-1-24-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-23\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-1267\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#9edcff\",\n"
        "                \"inFrame\": 219,\n"
        "                \"outFrame\": 232,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"solid-1-23-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-22\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-1316\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#ffe8a9\",\n"
        "                \"inFrame\": 227,\n"
        "                \"outFrame\": 241,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"solid-1-22-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-21\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-1285\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#7dffe2\",\n"
        "                \"inFrame\": 235,\n"
        "                \"outFrame\": 252,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 0.5\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"solid-1-21-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-20\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-600\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 252,\n"
        "                \"outFrame\": 273,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-20-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-19\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 2,\n"
        "                \"srcId\": \"image-128\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 273,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-19-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-18\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-921\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#d2ffcc\",\n"
        "                \"inFrame\": 273,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 136,\n"
        "                        \"dy\": 240,\n"
        "                        \"sx\": 0.5,\n"
        "                        \"sy\": 0.5,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-17\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 2,\n"
        "                \"srcId\": \"image-128\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 273,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-17-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-16\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-816\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#ffb4e7\",\n"
        "                \"inFrame\": 273,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 136,\n"
        "                        \"dy\": 720,\n"
        "                        \"sx\": 0.5,\n"
        "                        \"sy\": 0.5,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-15\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 2,\n"
        "                \"srcId\": \"image-128\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 273,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-15-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-14\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-770\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#fff4c2\",\n"
        "                \"inFrame\": 273,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 408,\n"
        "                        \"dy\": 240,\n"
        "                        \"sx\": 0.5,\n"
        "                        \"sy\": 0.5,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-13\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 2,\n"
        "                \"srcId\": \"image-128\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"matte\": 1,\n"
        "                \"inFrame\": 273,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-13-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-12\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 32768,\n"
        "                \"srcId\": \"solid-862\",\n"
        "                \"blend\": 0,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#bedeff\",\n"
        "                \"inFrame\": 273,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 408,\n"
        "                        \"dy\": 720,\n"
        "                        \"sx\": 0.5,\n"
        "                        \"sy\": 0.5,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-11\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-770\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#fff4c2\",\n"
        "                \"inFrame\": 289,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 408,\n"
        "                        \"dy\": 240,\n"
        "                        \"sx\": 0.5,\n"
        "                        \"sy\": 0.5,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-10\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-816\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#ffb4e7\",\n"
        "                \"inFrame\": 289,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 136,\n"
        "                        \"dy\": 720,\n"
        "                        \"sx\": 0.5,\n"
        "                        \"sy\": 0.5,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-9\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-921\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#d2ffcc\",\n"
        "                \"inFrame\": 289,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 136,\n"
        "                        \"dy\": 240,\n"
        "                        \"sx\": 0.5,\n"
        "                        \"sy\": 0.5,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-8\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-862\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"color\": \"#bedeff\",\n"
        "                \"inFrame\": 289,\n"
        "                \"outFrame\": 304,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 408,\n"
        "                        \"dy\": 720,\n"
        "                        \"sx\": 0.5,\n"
        "                        \"sy\": 0.5,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-7\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-61\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"inFrame\": 304,\n"
        "                \"outFrame\": 334,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 240,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 240,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-6\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-61\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"inFrame\": 304,\n"
        "                \"outFrame\": 334,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 240,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 720,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-5\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-1137\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"color\": \"#f0c4ff\",\n"
        "                \"inFrame\": 319,\n"
        "                \"outFrame\": 334,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 240,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 240,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"solid-1-4\",\n"
        "                \"type\": 3,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"solid-1552\",\n"
        "                \"blend\": 12,\n"
        "                \"width\": 544,\n"
        "                \"height\": 480,\n"
        "                \"color\": \"#ffd6aa\",\n"
        "                \"inFrame\": 319,\n"
        "                \"outFrame\": 334,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 240,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 720,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-3\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-99\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 334,\n"
        "                \"outFrame\": 368,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-3-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"image-1-2\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"image-99\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 334,\n"
        "                \"outFrame\": 368,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": true,\n"
        "                    \"filename\": \"image-1-2-transform2d.json\"\n"
        "                }\n"
        "            },\n"
        "            {\n"
        "                \"uid\": \"photo-1-1\",\n"
        "                \"type\": 2,\n"
        "                \"flags\": 0,\n"
        "                \"srcId\": \"photo-1412\",\n"
        "                \"blend\": 1,\n"
        "                \"width\": 544,\n"
        "                \"height\": 960,\n"
        "                \"inFrame\": 0,\n"
        "                \"outFrame\": 368,\n"
        "                \"opacity\": {\n"
        "                    \"animated\": false,\n"
        "                    \"value\": 1\n"
        "                },\n"
        "                \"transform\": {\n"
        "                    \"animated\": false,\n"
        "                    \"atom\": {\n"
        "                        \"ax\": 272,\n"
        "                        \"ay\": 480,\n"
        "                        \"dx\": 272,\n"
        "                        \"dy\": 480,\n"
        "                        \"sx\": 1,\n"
        "                        \"sy\": 1,\n"
        "                        \"rz\": 0\n"
        "                    }\n"
        "                }\n"
        "            }\n"
        "        ]\n"
        "    }\n"
        "]");

char *mask = const_cast<char *>("{\n"
        "    \"masks\": [\n"
        "        {\n"
        "            \"uid\": \"image-1-34\",\n"
        "            \"width\": 544,\n"
        "            \"height\": 960,\n"
        "            \"inPoint\": 147,\n"
        "            \"outPoint\": 186,\n"
        "            \"filename\": \"mask-image-1-34.json\"\n"
        "        }\n"
        "    ],\n"
        "    \"webps\": [\n"
        "        {\n"
        "            \"srcId\": \"photo-1412\",\n"
        "            \"width\": 544,\n"
        "            \"height\": 960,\n"
        "            \"inFrame\": 0,\n"
        "            \"outFrame\": 368,\n"
        "            \"filename\": \"animation-1412.webp\"\n"
        "        }\n"
        "    ],\n"
        "    \"photos\": [\n"
        "        \n"
        "    ],\n"
        "    \"videos\": [\n"
        "        \n"
        "    ]\n"
        "}");

void callJavaLogMethod(char *line);

